services:
  sopds:
    image: sopds:latest
    container_name: sopds
    hostname: sopds
    restart: always
    env_file:
      - .env
    volumes:
      - "./library:/library:ro"
      - "./db:/var/lib/pgsql"
    ports:
      - "100:80"
